### ISSUE TITLE
pull code มาแล้ว run ไม่ได้ ไม่ใส่ firebase.config.js อันนี้มาให้อ่า จบกั๊นนน

### ISSUE THREAD

**Issue by Thanakorn-ki** [Sellsuki/rorder#27]

**Comment by biigpongsatorn** [comment]
มันเป็น credentail ของ firebase อ่า ไม่ได้เอาขึ้น git

**Comment by Thanakorn-ki** [comment]
แวะมาเอาเขียว ฮาๆ ปล.แต่กะว่าจะเพิ่ม feature Clipboard URL ครับ

**Comment by biigpongsatorn** [comment]
หลังไมค์หาจารเนเลยขอ credential แก 5555
